<a href="https://colab.research.google.com/github/Shilpa-collab-bot/Shilpa-collab-bot-/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np



In [ ]:

arr1=np.array([[1,2,3,4],[5,6,7,80]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7, 80]])

In [ ]:
arr2=np.array([[10,20,30,40,100],
               [50,60,70,80,200]])
arr2

array([[ 10,  20,  30,  40, 100],
       [ 50,  60,  70,  80, 200]])

In [ ]:
arr1.reshape((4,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7, 80]])

In [ ]:
arr1.reshape((8,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [80]])

In [ ]:
arr1.reshape((1,8))

array([[ 1,  2,  3,  4,  5,  6,  7, 80]])

In [ ]:
arr2.reshape((2,5))

array([[ 10,  20,  30,  40, 100],
       [ 50,  60,  70,  80, 200]])

In [ ]:
arr2.reshape((5,2))

array([[ 10,  20],
       [ 30,  40],
       [100,  50],
       [ 60,  70],
       [ 80, 200]])

In [ ]:
arr2.reshape((10,1))

array([[ 10],
       [ 20],
       [ 30],
       [ 40],
       [100],
       [ 50],
       [ 60],
       [ 70],
       [ 80],
       [200]])

In [ ]:
arr2.reshape((1,10))

array([[ 10,  20,  30,  40, 100,  50,  60,  70,  80, 200]])

In [ ]:
arr3=np.array([[[1,2,3,4,5],
                [5,6,7,8,9],
                [10,11,12,13,14]]])
arr3


array([[[ 1,  2,  3,  4,  5],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [ ]:
arr3.reshape((3,5))

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr3.reshape((5,3))

array([[ 1,  2,  3],
       [ 4,  5,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
arr3.reshape((1,15))

array([[ 1,  2,  3,  4,  5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [ ]:
arr3.reshape((15,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [ ]:
arr4=np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]],
               [[13,14,15],[16,17,18]]])
arr4


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [ ]:
#ndim is in built function which gives the dimension of an array
arr2.ndim

2

In [ ]:
arr4.shape

(3, 2, 3)

In [ ]:
arr3.shape

(1, 3, 5)

In [ ]:
arr2.shape

(2, 5)

In [ ]:
arr11=np.array([1,2])
arr11

array([1, 2])

In [ ]:
#shape-->(values,)
arr11.shape

(2,)

In [ ]:
arr22=np.array([[1,2,3,4],[5,6,7,8]])
arr22

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#shape-->(rows,cols)
arr22.shape

(2, 4)

In [ ]:
arr33=np.array([[[1,2,3,4,5],[6,7,8,9,10]],
                [[11,12,13,14,15],[16,17,18,19,20]]])
arr33

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [ ]:
#shape-->(rows,cols,values)
arr33.shape

(2, 2, 5)

In [ ]:
#zeros -->1d
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#zeros-->2D
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
#zeros-->3D
np.zeros((1,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
#it choice randomly
l=[1,2,"Hai","Hello",2+10j]
np.random.choice(l)
l

[1, 2, 'Hai', 'Hello', (2+10j)]

In [ ]:
#it give positive and negative
np.random.randn(10)

array([-0.03568159,  0.71627048, -0.43323783,  1.24610716,  0.64303941,
        1.55235675, -0.02058187,  0.46303311,  0.12373238, -0.79461006])

In [ ]:
#It give only positive
np.random.rand(1000)

In [ ]:
#return an array with random values with in the specified limits
np.random.randint(1,100,100)

array([37,  9,  5, 18, 17,  8, 12, 86, 35, 27, 54, 74,  5, 51, 37, 63, 50,
       83, 55, 45, 81, 96,  1, 20,  4, 61, 65, 61, 63, 57,  9,  9, 92, 26,
       68, 88, 76, 73, 76, 34, 18,  9, 76, 11, 85, 78, 33, 85, 15, 77, 76,
       47, 83, 11, 82, 22, 33, 82, 66, 44, 65, 79, 56, 39, 33, 13, 38, 58,
       26,  5, 87, 65, 30, 92, 66, 10, 33, 14, 96,  9, 78, 37, 43,  9, 48,
       75, 90, 42, 48, 59, 57, 77, 25, 81,  6, 81, 29, 12, 44, 51])

In [ ]:
np.random.randint(-11,-1,10)

array([ -5,  -7,  -9,  -4,  -4, -11,  -7,  -6, -11,  -3])

In [ ]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
#arange(start,end,step)
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(-10,10,1)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
l=[10,'hello',2.02,2+3j]
np.random.shuffle(l)
l

[2.02, 10, (2+3j), 'hello']

In [ ]:
l=np.array([1,"shilpa",2.4,3+4j])
np.random.shuffle(l)
l

array(['1', '(3+4j)', '2.4', 'shilpa'], dtype='<U64')

In [ ]:
arr6=np.array([1,2,4,6])
arr6.dtype
arr7=np.array([1.0,5.6,4.9,6.3])
arr7.dtype

dtype('float64')

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
a=np.array([1,2,4])
a.ndim

1

In [ ]:
b=np.identity(3)

b.ndim
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr=np.array([x for x in np.arange(5,15) if x%2==0])
arr

array([ 6,  8, 10, 12, 14])

In [ ]:
arr=np.array([chr(x+97) for x in np.arange(0,25)])
arr

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
       'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y'],
      dtype='<U1')

In [ ]:
#indexing-with the help of sub address we get value from a colletion
#index-subabbress
arr1=np.array([10,20,30,40,50,60,70,80,90,100])
arr1[1]
arr1[-10]
arr1[5]
#index out of the bound
#syntax arr[index]

np.int64(60)

In [ ]:
#syntax arr[row_index,col_index]
arr2=np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12],
               [13,14,15,16]])
arr2[1,3]
arr2[3,3]
arr2[1,1]
arr2[0,3]
arr2[-1,-1]
arr2[-3,-1]
arr2[-2,-3]
arr2[-3,-4]
arr2[-4,-4]

np.int64(1)

In [ ]:
#syntax arr[row_index,col_index,value_index]
arr3=np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]],
               [[13,14,15],[16,17,18]]
               ])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [ ]:
arr3[2,0,1]
arr3[0,0,2]
arr3[2,1,1]
arr3[2,0,0]
arr3[-1,-2,-2]
arr3[-3,-1,-1]
arr3[-2,-2,-3]
arr3[-2,-1,-1]

np.int64(12)

#arr[startindex:endindex +-1:update]
#arr[row_slice:,col_slice:]
#arr[row_slice:,col_slice: ,val_slice:]

In [ ]:
#arr[startindex:endindex +-1:update]
#arr[row_slice:,col_slice:]
#arr[row_slice:,col_slice: ,val_slice:]
arr=np.array([10,20,30,40,50,60,])
arr[2:]
arr[1:3]


array([20, 30])

In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],
              [[7,8,9],[10,11,12]],
              [[13,14,14],[15,16,17]]
              ])
arr[0:,0:1,0::]

array([[[ 1,  2,  3]],

       [[ 7,  8,  9]],

       [[13, 14, 14]]])

In [ ]:
arr[1:,1:,1::]

array([[[11, 12]],

       [[16, 17]]])

In [ ]:
arr[0:2,0:1,1:]

array([[[2, 3]],

       [[8, 9]]])

In [ ]:
arr[1:2,0:1,1::]

array([[[8, 9]]])

In [ ]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 14],
        [15, 16, 17]]])

In [ ]:
arr[0:,1:,0:]

array([[[ 4,  5,  6]],

       [[10, 11, 12]],

       [[15, 16, 17]]])

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[0:1,0:]

array([[1, 2, 3]])

In [ ]:
arr[1:,0:2]

array([[4, 5],
       [7, 8]])

In [ ]:
arr[-1:,-3:]

array([[7, 8, 9]])

In [ ]:
#operators
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr1+arr2

array([5, 7, 9])

In [ ]:
arr1-arr2

array([-3, -3, -3])

In [ ]:
arr1*arr2

array([ 4, 10, 18])

In [ ]:
arr1**arr2

array([  1,  32, 729])

In [ ]:
arr1/arr2

array([0.25, 0.4 , 0.5 ])

In [ ]:
arr1//arr2

array([0, 0, 0])

In [ ]:
arr1%arr2

array([1, 2, 3])

In [ ]:
#any() and all()
arr=np.array([1,0])
arr.any()


np.True_

In [ ]:
arr=np.array([0,0,0,0])
arr.any()

np.False_

In [ ]:
arr=np.array([1,2,3,4,0])
arr.all()

np.False_

In [ ]:
arr=np.array([1,2,3,4])
arr.all()

np.True_

In [ ]:
#bitwise operators
arr=np.array([1,2,3])
arr1=np.array([4,5,6])
np.bitwise_and(arr,arr1)

array([0, 0, 2])

In [ ]:
np.bitwise_or(arr,arr1)

array([5, 7, 7])

In [ ]:
np.bitwise_not(arr)

array([-2, -3, -4])

In [ ]:
np.bitwise_left_shift(arr,arr1)

array([ 16,  64, 192])

In [ ]:
np.bitwise_right_shift(arr,arr1)

array([0, 0, 0])

In [ ]:
arr&arr1

array([0, 0, 2])

In [ ]:
arr|arr1

array([5, 7, 7])

In [ ]:
~arr

array([-2, -3, -4])

In [ ]:
arr<<arr1

array([ 16,  64, 192])

In [ ]:
arr>>arr1

array([0, 0, 0])

In [ ]:
arr1=np.array([11,22,33])
arr2=np.array([32,43,56])
arr1==arr2

array([False, False, False])

In [ ]:
arr1!=arr2

array([ True,  True,  True])

In [ ]:
arr1>=arr2

array([False, False, False])

In [ ]:
arr1<=arr2

array([ True,  True,  True])

In [ ]:
arr1<arr2

array([ True,  True,  True])

In [ ]:
arr1>arr2

array([False, False, False])

In [ ]:
#array operations with inbuilt functions
arr1
arr1.sum() #np.int64(66)
arr1.mean() #np.float64(22.0)
arr1.min() #np.int64(11)
arr1.max() #np.int64(33)
arr1.size #3
len(arr1) #3

3

In [ ]:
#array operation with